In [1]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [2]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices() #실행 가능한 CPU, GPU

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 10946886165005307834
 xla_global_id: -1,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 2255958836
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 1927999624744558666
 physical_device_desc: "device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5"
 xla_global_id: 416903419]

In [4]:
#기본적으로 GPU로 실행됨
tf.debugging.set_log_device_placement(True)

a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
b = tf.constant([[1.0,2.0],[3.4,4.0],[5.0,6.0]])
c = tf.matmul(a,b)

print(c)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(
[[22.8 28. ]
 [51.  64. ]], shape=(2, 2), dtype=float32)


In [2]:
# 텐서플로 v2에서 gpu의 메모리를 설정하는 방법
import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
#gpu의 메모리를 점진적으로 늘리도록 설정
#tf.config.experimental.set_memory_growth(gpus[0], True)
#메모리 사용량을 직접 지정하는 방법
tf.config.experimental.set_virtual_device_configuration(gpus[0],
[tf.config.experimental.VirtualDeviceConfiguration(memory_limit=512)])

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [1]:
#텐서플로 2.0으로 코딩하는 방법
import tensorflow as tf
import sys
print(sys.version) #파이썬 버전
print(tf.__version__) #텐서플로우 버전

3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
2.7.0


In [2]:
#상수 선언
hello = tf.constant('Hello World')
print(hello)
print(hello.numpy()) # 바이트 배열
print(hello.numpy().decode('utf-8')) # str 클래스로 변환, b가 사라짐
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)

print(c.numpy())
print([a.numpy(), b.numpy(), c.numpy()])

tf.Tensor(b'Hello World', shape=(), dtype=string)
b'Hello World'
Hello World
42
[10, 32, 42]


In [3]:
node1 = tf.constant(3.0)
node2 = tf.constant(4.0)
node3 = tf.add(node1, node2)
print(node3.numpy())

7.0


In [4]:
def output(a, b):
    return tf.multiply(a, b)

print(output(3.0, 5.0).numpy())
print(output(0.0, 6.0).numpy())
print(output([20.,3.1,7.4], [6.0, 2.5, 3.1]).numpy())

15.0
0.0
[120.     7.75  22.94]


In [5]:
#텐서플로의 변수 선언
w = tf.Variable([0.3], dtype=tf.float32) #변수
b = tf.Variable([-0.3], dtype=tf.float32)

def linear_model(x):
    return tf.multiply(w, tf.add(x, b))

x=[1.,2.,3.,4.]
# x의 값에 따라 linear_model 계산
linear_model(x).numpy()

array([0.21000001, 0.51000005, 0.81000006, 1.11      ], dtype=float32)

In [3]:
import tensorflow as tf
import numpy as np

X = np.array([[1,2,3],[4,5,6]]) #2행 3열
print('X\n', X)

#3행 2열의 랜덤
w = np.array([[np.random.randint(10) for col in range(2)]
for row in range(3)])
print('W\n', w)

#2행 1열
b = np.array([[np.random.randint(10) for col in range(1)]
for row in range(2)])
print('b\n', b)

def expr(X):
    return tf.matmul(X, w) + b #matmul : 행렬 곱셈

print('Result\n', expr(X).numpy())

X
 [[1 2 3]
 [4 5 6]]
W
 [[0 0]
 [0 7]
 [8 9]]
b
 [[3]
 [9]]
Result
 [[27 44]
 [57 98]]


In [4]:
#실습 - 구구단
import tensorflow.compat.v1 as tf #구버전 텐서플로우
tf.disable_v2_behavior()

def gugu(dan):
    #플레이스홀더 선언(그래프에 입력할 변수)
    left = tf.placeholder(tf.int32)
    right = tf.placeholder(tf.int32)
    #그래프의 수식
    calc = tf.multiply(left, right)

    with tf.Session() as sess: # 세션이 생성됨
        for i in range(1, 10):
            #세션.run(실행함수, feed_dict={변수: 입력할 값})
            result = sess.run(calc, feed_dict={left: dan, right: 1})
            print('{0} x {1} = {2:2}'.format(dan, i, result))

gugu(7)

Instructions for updating:
non-resource variables are not supported in the long term
7 x 1 =  7
7 x 2 =  7
7 x 3 =  7
7 x 4 =  7
7 x 5 =  7
7 x 6 =  7
7 x 7 =  7
7 x 8 =  7
7 x 9 =  7


In [1]:
#tensorflow 2.0
import tensorflow as tf

def calc(left, right):
    return tf.multiply(left, right)

def gugu(dan):
    for i in range(1, 10):
        result = calc(dan, i)
        print('{0} x {1} = {2:2}'.format(dan, i, result))

In [2]:
gugu(7)

7 x 1 =  7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
