In [2]:
#손글씨 예측모형
from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 784).astype('float32') / 255.0
X_test = X_test.reshape(10000, 784).astype('float32') / 255.0

In [3]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train[:100], y_train[:100])

LogisticRegression()

In [4]:
print(model.score(X_train[:100], y_train[:100]))
print(model.score(X_test[:100], y_test[:100]))

1.0
0.72


In [6]:
#모형 저장
import pickle
pickle.dump(model, open('c:/data/mnist/mnist_logit.model', 'wb'))

In [7]:
#모형 불러오기
model = pickle.load(open('c:/data/mnist/mnist_logit.model', 'rb'))

#모형사용
pred = model.predict(X_test[:10])
print('예측값:', pred[:10])
print('실제값:', y_test[:10])

예측값: [7 2 1 0 4 1 9 4 4 9]
실제값: [7 2 1 0 4 1 4 9 5 9]


In [8]:
#혼동행렬 출력
from sklearn.metrics import confusion_matrix
import pandas as pd

pred = model.predict(X_test)

cm = confusion_matrix(y_test, pred)
df_cm = pd.DataFrame(cm, index= range(10),
columns=range(10))

df_cm

0     1    2    3    4    5    6    7    8    9
0  849     1    9    0   11   49   35   15    2    9
1    0  1090    1    2    0    1    0    0   36    5
2   23   226  568    3  115   11   14   22   39   11
3   15    47   47  795   10   16    3   11   31   35
4    2    12    1    0  821    0   19   11    1  115
5   60    28    9  267  132  244   29   38   45   40
6   22    40   13    1  185   26  649   10    0   12
7    3    57   21    9   18    7    0  800   19   94
8   39    68   67   67   66   16   22   10  471  148
9   14    10    7   39  351    2    1  118    4  463

In [1]:
#인공신경망(keras)
from tensorflow.keras.datasets import mnist
from keras.utils import np_utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#1.전처리
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 784).astype('float32') / 255.0
X_test = X_test.reshape(10000, 784).astype('float32') / 255.0

#원핫인코딩
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
print(y_train[:5])

X_val = X_train[:12600]
X_train = X_train[12600:]
y_val = y_train[:12600]
y_train = y_train[12600:]

#2.모델구성
model = Sequential()
#은닉층
model.add(Dense(units=512, input_dim=28*28, activation='relu'))

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [2]:
#출력층
model.add(Dense(units=10, activation='softmax'))

#3.모델 학습과정
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [3]:
# 4.모델 학습
hist = model.fit(X_train, y_train, epochs=5, batch_size=32,
validation_data=(X_val, y_val))

Epoch 1/5
1482/1482 [==============================] - 5s 3ms/step - loss: 0.6723 - accuracy: 0.8400 - val_loss: 0.3780 - val_accuracy: 0.9006
Epoch 2/5
1482/1482 [==============================] - 4s 3ms/step - loss: 0.3471 - accuracy: 0.9044 - val_loss: 0.3139 - val_accuracy: 0.9137
Epoch 3/5
1482/1482 [==============================] - 4s 3ms/step - loss: 0.2969 - accuracy: 0.9168 - val_loss: 0.2762 - val_accuracy: 0.9237
Epoch 4/5
1482/1482 [==============================] - 4s 3ms/step - loss: 0.2665 - accuracy: 0.9252 - val_loss: 0.2518 - val_accuracy: 0.9299
Epoch 5/5
1482/1482 [==============================] - 4s 3ms/step - loss: 0.2432 - accuracy: 0.9326 - val_loss: 0.2348 - val_accuracy: 0.9340


In [4]:
import numpy as np

# 5.모델 평가
loss_and_metrics = model.evaluate(X_test, y_test,
batch_size=32, verbose=0)
print('loss_and_metrics : ' + str(loss_and_metrics))

# 6.모델 저장
model.save('c:/data/mnist')

loss_and_metrics : [0.22542521357536316, 0.9348999857902527]
INFO:tensorflow:Assets written to: c:/data/mnist\assets
